apiVersion: apps/v1
kind: Deployment
metadata:
  name: gymserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gymserver
  template:
    metadata:
      labels:
        app: gymserver
    spec:
      containers:
        - name: gymserver
          image: gymserver:latest
          ports:
            - containerPort: 8080