version: '3.8'

services:
  gymserver:
    image: gymserver:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8887:8080"
    container_name: gymserver
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/start-postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    container_name: "db_gym"
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=start-postgres
    ports:
      - 5433:5432
volumes:
  db_data:
